---
services:
  agent:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: agent
    ports:
      - "8080:8080"
    volumes:
      - ./artifacts:/tmp/playwright/artifacts
    environment:
      BROWSER_USER_AGENT: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
      BROWSER_VIEWPORT_WIDTH: "1920"
      BROWSER_VIEWPORT_HEIGHT: "1080"
      BROWSER_HEADER_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
      BROWSER_HEADER_ACCEPT_LANGUAGE: "en-US,en;q=0.9"
      BROWSER_HEADER_ACCEPT_ENCODING: "gzip, deflate, br"
      BROWSER_HEADER_DNT: "1"
      BROWSER_HEADER_CONNECTION: "keep-alive"
      BROWSER_HEADER_UPGRADE_INSECURE_REQUESTS: "1"
      BROWSER_ARGS: >-
        --disable-blink-features=AutomationControlled
        --disable-features=VizDisplayCompositor
        --no-first-run
        --disable-default-apps
        --disable-extensions
        --disable-plugins
        --disable-sync
        --disable-translate
        --hide-scrollbars
        --mute-audio
        --no-zygote
        --disable-background-timer-throttling
        --disable-backgrounding-occluded-windows
        --disable-renderer-backgrounding
        --disable-ipc-flooding-protection
      A2A_PORT: 8080
      A2A_DEBUG: true
      A2A_AGENT_URL: http://localhost:8080
      A2A_STREAMING_STATUS_UPDATE_INTERVAL: 1s
      A2A_SERVER_READ_TIMEOUT: 120s
      A2A_SERVER_WRITE_TIMEOUT: 120s
      A2A_SERVER_IDLE_TIMEOUT: 120s
      A2A_SERVER_DISABLE_HEALTHCHECK_LOG: true
      A2A_AGENT_CARD_FILE_PATH: .well-known/agent-card.json
      A2A_AGENT_CLIENT_PROVIDER: ${A2A_AGENT_CLIENT_PROVIDER}
      A2A_AGENT_CLIENT_MODEL: ${A2A_AGENT_CLIENT_MODEL}
      A2A_AGENT_CLIENT_API_KEY: ""
      A2A_AGENT_CLIENT_BASE_URL: http://inference-gateway:8080/v1
      A2A_AGENT_CLIENT_TIMEOUT: 30s
      A2A_AGENT_CLIENT_MAX_RETRIES: 3
      A2A_AGENT_CLIENT_MAX_CHAT_COMPLETION_ITERATIONS: 20
      A2A_AGENT_CLIENT_MAX_TOKENS: 4096
      A2A_AGENT_CLIENT_TEMPERATURE: 0.7
      A2A_CAPABILITIES_STREAMING: true
      A2A_CAPABILITIES_PUSH_NOTIFICATIONS: false
      A2A_CAPABILITIES_STATE_TRANSITION_HISTORY: false
      A2A_TASK_RETENTION_MAX_COMPLETED_TASKS: 100
      A2A_TASK_RETENTION_MAX_FAILED_TASKS: 50
      A2A_TASK_RETENTION_CLEANUP_INTERVAL: 5m
      A2A_QUEUE_PROVIDER: memory
      A2A_QUEUE_URL: ""
      A2A_QUEUE_MAX_SIZE: 100
      A2A_QUEUE_CLEANUP_INTERVAL: 500s
      A2A_AUTH_ENABLE: false
    networks:
      - a2a-network

  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    container_name: inference-gateway
    environment:
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      ENVIRONMENT: development
      SERVER_READ_TIMEOUT: 530s
      SERVER_WRITE_TIMEOUT: 530s
      CLIENT_TIMEOUT: 530s
      CLIENT_IDLE_CONN_TIMEOUT: 130s
      CLIENT_RESPONSE_HEADER_TIMEOUT: 120s
    networks:
      - a2a-network

  cli:
    image: ghcr.io/inference-gateway/cli:latest
    pull_policy: always
    environment:
      INFER_LOGGING_DEBUG: true
      INFER_GATEWAY_URL: http://inference-gateway:8080
      INFER_A2A_ENABLED: true
      INFER_TOOLS_ENABLED: false
      INFER_AGENT_MODEL: deepseek/deepseek-chat
      INFER_A2A_AGENTS: |
        http://agent:8080
    command:
      - chat
    networks:
      - a2a-network
    profiles:
      - manual

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://agent:8080
      - --timeout
      - 500s
    networks:
      - a2a-network
    profiles:
      - manual

  demo-site:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./demo-site:/usr/share/nginx/html:ro
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge
