# Code generated by ADL CLI v0.21.6. DO NOT EDIT.
# This file was automatically generated from an ADL (Agent Definition Language) specification.
# Manual changes to this file may be overwritten during regeneration.

FROM golang:1.25-alpine AS builder

# Build arguments for version injection
ARG VERSION="0.1.3"
ARG AGENT_NAME="browser-agent"
ARG AGENT_DESCRIPTION="AI agent for browser automation and web testing using Playwright"

WORKDIR /app

# Install ca-certificates for HTTPS requests
RUN apk --no-cache add ca-certificates

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Install playwright CLI with right version for later use
RUN PWGO_VER=$(grep -oE "playwright-go v[0-9]+\.[0-9]+\.[0-9]+" /app/go.mod | sed 's/playwright-go v//g') \
    && go install github.com/playwright-community/playwright-go/cmd/playwright@v${PWGO_VER}

# Copy source code
COPY . .

# Build the application with optimized LDD flags and version injection
RUN CGO_ENABLED=0 GOOS=linux go build \
    -a \
    -installsuffix cgo \
    -ldflags="-s -w -extldflags '-static' \
        -X 'main.Version=${VERSION}' \
        -X 'main.AgentName=${AGENT_NAME}' \
        -X 'main.AgentDescription=${AGENT_DESCRIPTION}'" \
    -trimpath \
    -o main .

# Stage 2: Final image with browser dependencies
FROM ubuntu:24.04

# Install system dependencies and browsers
RUN apt-get update && apt-get install -y \
    ca-certificates \
    tzdata \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/

# Copy the binary and playwright CLI from builder stage
COPY --from=builder /app/main .
COPY --from=builder /go/bin/playwright /usr/local/bin/playwright

# Copy agent card
COPY --from=builder /app/.well-known ./.well-known

# Install only Chromium browser with dependencies
RUN playwright install --with-deps chromium

# Expose port
EXPOSE 8080

# Set environment variables
ENV A2A_SERVER_PORT=8080

# Run the application
CMD ["./main"]
