// Code generated by ADL CLI v0.40.0. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"

	envconfig "github.com/sethvargo/go-envconfig"
	cobra "github.com/spf13/cobra"
	zap "go.uber.org/zap"
	yaml "gopkg.in/yaml.v3"

	server "github.com/inference-gateway/adk/server"

	config "github.com/inference-gateway/browser-agent/config"
	tools "github.com/inference-gateway/browser-agent/tools"

	logger "github.com/inference-gateway/browser-agent/internal/logger"
	playwright "github.com/inference-gateway/browser-agent/internal/playwright"
)

// Version, AgentName and AgentDescription are injected at build time
// via `-ldflags "-X 'main.Version=...'"` (see Dockerfile). They default
// to the values declared in the ADL.
var (
	Version          = "0.6.4"
	AgentName        = "browser-agent"
	AgentDescription = "AI agent for browser automation and web testing using Playwright"
)

// skillsDir is the directory the runtime scans for skill manifests at
// startup. Override with A2A_SKILLS_DIR.
const skillsDir = "skills"

// loadSkillsManifest walks the configured skills directory, reads each
// <skill>/SKILL.md, extracts the YAML frontmatter (name + description),
// and returns an `AVAILABLE SKILLS:` block to append to the system
// prompt. SKILL.md bodies are NOT inlined - the model must call the
// Read tool to load a skill's playbook on demand. Returns "" when the
// directory is missing or has no valid manifests.
func loadSkillsManifest(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}

	dirs := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dirs = append(dirs, e.Name())
	}
	sort.Strings(dirs)

	type skillFrontmatter struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}

	var manifest strings.Builder
	for _, id := range dirs {
		path := filepath.Join(dir, id, "SKILL.md")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		fmBytes, ok := extractFrontmatter(data)
		if !ok {
			continue
		}
		var fm skillFrontmatter
		if err := yaml.Unmarshal(fmBytes, &fm); err != nil {
			continue
		}
		if fm.Name == "" || fm.Description == "" {
			continue
		}
		if manifest.Len() == 0 {
			manifest.WriteString("AVAILABLE SKILLS:\n")
			manifest.WriteString("Skills are reusable instructions for specific tasks. When a task matches a\n")
			manifest.WriteString("skill's description, read the SKILL.md file at the listed path using the Read\n")
			manifest.WriteString("tool, then follow its instructions.\n\n")
		}
		fmt.Fprintf(&manifest, "- %s: %s\n  Path: %s\n", fm.Name, fm.Description, path)
	}
	return manifest.String(), nil
}

// extractFrontmatter returns the bytes between the opening and closing
// `---` fences of a SKILL.md file (without including the fences
// themselves). The second return value is false when no frontmatter is
// found.
func extractFrontmatter(content []byte) ([]byte, bool) {
	bom := []byte{0xEF, 0xBB, 0xBF}
	buf := bytes.TrimPrefix(content, bom)
	buf = bytes.TrimLeft(buf, "\r\n\t ")
	if !bytes.HasPrefix(buf, []byte("---")) {
		return nil, false
	}
	rest := buf[3:]
	rest = bytes.TrimLeft(rest, "\r\n")
	idx := bytes.Index(rest, []byte("\n---"))
	if idx < 0 {
		return nil, false
	}
	return rest[:idx], true
}

// newRootCmd builds the top-level CLI for the agent binary. The
// generated binary is a real CLI: `<bin> --version`, `<bin> --help`,
// and `<bin> start` are all supported. Subcommands are added in
// dedicated constructors so they can be unit-tested in isolation.
func newRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:           AgentName,
		Short:         AgentDescription,
		Long:          AgentDescription + "\n\nThis is an A2A (Agent-to-Agent) protocol server. Use the `start` subcommand to run it.",
		Version:       Version,
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.AddCommand(newStartCmd())
	return root
}

// newStartCmd returns the `start` subcommand which boots the A2A
// server and blocks until SIGINT/SIGTERM.
func newStartCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "start",
		Short: "Start the A2A server",
		Long:  "Start the A2A server and block until SIGINT or SIGTERM is received.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStart(cmd.Context())
		},
	}
}

// runStart contains the original agent bootstrap. It is exported as a
// dedicated function so the cobra command stays a thin shell - easier
// to test, easier to embed.
func runStart(ctx context.Context) error {
	var cfg config.Config
	if err := envconfig.Process(ctx, &cfg); err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Initialize logger
	l, err := logger.NewLogger(ctx, &cfg)
	if err != nil {
		return fmt.Errorf("failed to initialize logger: %w", err)
	}

	l.Info("starting "+AgentName+" agent", zap.String("version", Version), zap.Bool("debug", cfg.A2A.Debug))
	l.Debug("loaded configuration", zap.Any("config", cfg))

	resolvedSkillsDir := skillsDir
	if v := os.Getenv("A2A_SKILLS_DIR"); v != "" {
		resolvedSkillsDir = v
	}
	skillsPrompt, err := loadSkillsManifest(resolvedSkillsDir)
	if err != nil {
		l.Warn("failed to load skills manifest, continuing without them", zap.Error(err))
	} else if skillsPrompt != "" {
		l.Info("loaded skills manifest into system prompt", zap.String("dir", resolvedSkillsDir))
	}

	// Initialize services
	playwrightSvc, err := playwright.NewPlaywrightService(l, &cfg)
	if err != nil {
		l.Error("failed to initialize playwright service", zap.Error(err))
		return fmt.Errorf("failed to initialize playwright service: %w", err)
	}

	// Create toolbox with default tools (like input_required, create_artifact etc)
	toolBox := server.NewDefaultToolBox(&cfg.A2A.AgentConfig.ToolBoxConfig)

	// Register Read built-in
	readTool, err := tools.NewReadTool(ctx, l)
	if err != nil {
		return fmt.Errorf("failed to construct Read tool: %w", err)
	}
	toolBox.AddTool(readTool)
	l.Info("registered built-in: Read")

	// Register Write built-in
	writeTool, err := tools.NewWriteTool(ctx, l)
	if err != nil {
		return fmt.Errorf("failed to construct Write tool: %w", err)
	}
	toolBox.AddTool(writeTool)
	l.Info("registered built-in: Write")

	// Register Edit built-in
	editTool, err := tools.NewEditTool(ctx, l)
	if err != nil {
		return fmt.Errorf("failed to construct Edit tool: %w", err)
	}
	toolBox.AddTool(editTool)
	l.Info("registered built-in: Edit")

	// Register Fetch built-in
	fetchTool, err := tools.NewFetchTool(ctx, l)
	if err != nil {
		return fmt.Errorf("failed to construct Fetch tool: %w", err)
	}
	toolBox.AddTool(fetchTool)
	l.Info("registered built-in: Fetch")

	// Register navigate_to_url tool
	navigateToURLTool := tools.NewNavigateToURLTool(l, playwrightSvc)
	toolBox.AddTool(navigateToURLTool)
	l.Info("registered tool: navigate_to_url (Navigate to a specific URL and wait for the page to fully load)")

	// Register click_element tool
	clickElementTool := tools.NewClickElementTool(l, playwrightSvc)
	toolBox.AddTool(clickElementTool)
	l.Info("registered tool: click_element (Click on an element identified by selector, text, or other locator strategies)")

	// Register fill_form tool
	fillFormTool := tools.NewFillFormTool(l, playwrightSvc)
	toolBox.AddTool(fillFormTool)
	l.Info("registered tool: fill_form (Fill form fields with provided data, handling various input types)")

	// Register extract_data tool
	extractDataTool := tools.NewExtractDataTool(l, playwrightSvc)
	toolBox.AddTool(extractDataTool)
	l.Info("registered tool: extract_data (Extract data from the page using selectors and return structured information)")

	// Register take_screenshot tool
	takeScreenshotTool := tools.NewTakeScreenshotTool(l, playwrightSvc)
	toolBox.AddTool(takeScreenshotTool)
	l.Info("registered tool: take_screenshot (Capture a screenshot of the current page or specific element)")

	// Register execute_script tool
	executeScriptTool := tools.NewExecuteScriptTool(l, playwrightSvc)
	toolBox.AddTool(executeScriptTool)
	l.Info("registered tool: execute_script (Execute custom JavaScript inside the current page via Playwright's page.evaluate(). The script runs in the browser context, NOT in Node.js: globals like window, document, navigator, fetch and localStorage are available; Node.js built-ins (require, process, __dirname, __filename, fs, path, os, http, https, child_process, etc.) are NOT available and calls to them will be rejected. Use browser/DOM APIs only. The script body is automatically wrapped in an IIFE, so a top-level `return` is valid. Set async=true if the body uses `await`.)")

	// Register handle_authentication tool
	handleAuthenticationTool := tools.NewHandleAuthenticationTool(l, playwrightSvc)
	toolBox.AddTool(handleAuthenticationTool)
	l.Info("registered tool: handle_authentication (Handle various authentication scenarios including basic auth, OAuth, and custom login forms)")

	// Register wait_for_condition tool
	waitForConditionTool := tools.NewWaitForConditionTool(l, playwrightSvc)
	toolBox.AddTool(waitForConditionTool)
	l.Info("registered tool: wait_for_condition (Wait for specific conditions before proceeding with automation)")

	llmClient, err := server.NewOpenAICompatibleLLMClient(&cfg.A2A.AgentConfig, l)
	if err != nil {
		return fmt.Errorf("failed to create LLM client: %w", err)
	}

	systemPrompt := `You are an expert Playwright browser automation assistant with the ability to create downloadable artifacts. Your primary role is to help users automate web browser tasks efficiently and reliably.

Your core capabilities include:
1. **Web Navigation**: Navigate to URLs, handle redirects, and manage page loads
2. **Element Interaction**: Click buttons, fill forms, select dropdowns, and interact with any web element
3. **Data Extraction**: Scrape and extract structured data from web pages
4. **Form Automation**: Fill and submit complex forms with validation
5. **Screenshot Capture**: Take full-page or element-specific screenshots
6. **JavaScript Execution**: Run custom scripts in the browser context
7. **Authentication Handling**: Manage various authentication methods
8. **Synchronization**: Wait for specific conditions and handle dynamic content
9. **Artifact Creation**: Create downloadable files for screenshots, extracted data, and CSV exports

Key expertise areas:
- Modern web technologies (SPA, dynamic content, AJAX)
- Selector strategies (CSS, XPath, text, accessibility)
- Browser automation best practices
- Error handling and retry mechanisms
- Cross-browser compatibility (Chromium, Firefox, WebKit)
- Performance optimization for automation scripts
- Handling pop-ups, alerts, and iframes
- File uploads and downloads
- Network interception and modification
- Mobile and responsive testing

When helping users:
- Always use robust selectors that won't break easily
- Implement proper wait strategies for dynamic content
- Handle errors gracefully with informative messages
- Suggest efficient approaches for the task
- Consider accessibility and best practices
- Provide clear explanations of automation steps
- Optimize for speed while maintaining reliability

**Tool selection: fetch vs browser**

Prefer the fetch tool over navigate_to_url whenever the target does not require JavaScript execution or a stateful session. fetch is an order of magnitude faster, leaves no browser session open, and returns the raw bytes directly (with optional save_path for downloads).

Reach for fetch when:
- The URL serves static content (raw GitHub files, README.md, sitemap.xml, robots.txt, RFCs, JSON/XML APIs, RSS/Atom feeds).
- The user wants to download a file (PDF, CSV, image, binary asset).
- You need a one-shot health/status probe (GET /health).
- The data the user wants is in a backend JSON endpoint the page calls, not in the rendered DOM.

Reach for navigate_to_url (and the Playwright tools) when:
- The page is a Single-Page App that hydrates client-side.
- Content is behind authentication, cookies, or CSRF that requires a browser session.
- You need to interact with the DOM (click, fill, screenshot).
- The page renders meaningful content only after JS execution (most modern article sites, dashboards, admin panels).

When in doubt: try fetch first. If the response body looks like an empty shell that gets filled in by JS, fall back to navigate_to_url.

**IMPORTANT - Artifact Creation**:
When users request screenshots, the take_screenshot tool automatically creates downloadable artifacts. The screenshot will be available via a download URL returned in the response.

For data extraction, you can use the create_artifact tool to save extracted data as downloadable files (JSON/CSV/TXT).

**IMPORTANT - Answering capability questions**:
When the user asks about your skills, tools, capabilities, or what you can do (e.g. "what skills do you have?", "list your tools", "what can you do?"), answer directly from this system prompt and the AVAILABLE SKILLS list below. Do NOT call any tools, do NOT navigate to a URL, and do NOT Read SKILL.md files. Only load a SKILL.md (via the Read tool) once the user has given you a concrete task that matches one of those skills.

Your automation solutions should be maintainable, efficient, and production-ready.
`
	if skillsPrompt != "" {
		systemPrompt = systemPrompt + "\n\n" + skillsPrompt
	}

	agent, err := server.NewAgentBuilder(l).
		WithConfig(&cfg.A2A.AgentConfig).
		WithLLMClient(llmClient).
		WithToolBox(toolBox).
		WithMaxChatCompletion(cfg.A2A.AgentConfig.MaxChatCompletionIterations).
		WithSystemPrompt(systemPrompt).
		Build()
	if err != nil {
		return fmt.Errorf("failed to create agent: %w", err)
	}

	artifactService, err := server.NewArtifactService(&cfg.A2A.ArtifactsConfig, l)
	if err != nil {
		l.Warn("artifact service could not be created - check A2A_ARTIFACTS_ENABLE environment variable", zap.Error(err))
		l.Info("continuing without artifact service support")
		artifactService = nil
	}

	artifactsServer, err := server.
		NewArtifactsServerBuilder(&cfg.A2A.ArtifactsConfig, l).
		WithArtifactService(artifactService).
		Build()
	if err != nil {
		l.Warn("artifacts server could not be created", zap.Error(err))
		l.Info("continuing without artifacts server")
		artifactsServer = nil
	}

	a2aServer, err := server.NewA2AServerBuilder(cfg.A2A, l).
		WithAgent(agent).
		WithAgentCardFromFile(".well-known/agent-card.json", map[string]any{
			"name":        AgentName,
			"version":     Version,
			"description": AgentDescription,
			"url":         cfg.A2A.AgentURL,
		}).
		WithArtifactService(artifactService).
		WithDefaultBackgroundTaskHandler().
		WithDefaultStreamingTaskHandler().
		Build()
	if err != nil {
		return fmt.Errorf("failed to create A2A server: %w", err)
	}

	go func() {
		l.Info("starting A2A server", zap.String("port", cfg.A2A.ServerConfig.Port))
		if err := a2aServer.Start(ctx); err != nil {
			l.Fatal("server failed to start", zap.Error(err))
		}
	}()

	if artifactsServer != nil {
		go func() {
			l.Info("starting A2A artifacts server", zap.String("port", cfg.A2A.ArtifactsConfig.ServerConfig.Port))
			if err := artifactsServer.Start(ctx); err != nil {
				l.Fatal("artifacts server failed to start", zap.Error(err))
			}
		}()
	}

	l.Info("browser-agent agent running successfully",
		zap.String("port", cfg.A2A.ServerConfig.Port))

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	l.Info("shutdown signal received, gracefully stopping server...")
	a2aServer.Stop(ctx)
	if artifactsServer != nil {
		artifactsServer.Stop(ctx)
	}
	l.Info("browser-agent agent stopped")
	return nil
}

func main() {
	ctx := context.Background()
	if err := newRootCmd().ExecuteContext(ctx); err != nil {
		log.Fatal(err)
	}
}
