// Code generated by ADL CLI v0.20.17. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package config

import (
	serverConfig "github.com/inference-gateway/adk/server/config"
)

// Config represents the application configuration
type Config struct {
	// Core application settings
	Environment string `env:"ENVIRONMENT"`

	// A2A configuration (all A2A_ prefixed vars)
	A2A serverConfig.Config `env:",prefix=A2A_"`

	// Custom configuration sections
	Screenshots ScreenshotsConfig `env:",prefix=SCREENSHOTS_"`
}

// ScreenshotsConfig represents the screenshots configuration
type ScreenshotsConfig struct {
	Dir string `env:"DIR,default=/tmp/screenshots"`
}
